package com.advancedjava.springbootmvc;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;

public class DarkmodeTest {
    JavascriptExecutor js;
    private WebDriver driver;
    private Map<String, Object> vars;

    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "C:\\Users\\micka\\Downloads\\chromedriver_win32\\chromedriver.exe");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void darkmode() {
        driver.get("https://www.20minutes.fr/");
        driver.manage().window().setSize(new Dimension(968, 1020));
        driver.findElement(By.cssSelector(".mbrs-btnSwitch-wrapper")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".mbrs-btnSwitch-wrapper"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.cssSelector(".mbrs-modal-close > svg")).click();
        driver.findElement(By.linkText("Economie")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".block-list-item:nth-child(4) > .card-lined .teaser-headline"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.cssSelector(".block-list-item:nth-child(3) > .card-lined .teaser-title"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
    }
}
